version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - fullplexnet

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    networks:
      - fullplexnet

networks:
  fullplexnet:
    driver: bridge
